### PR TITLE
WIP: CI: Test on Travis

### PR DESCRIPTION
**Pull request by splattael**
Let's test `minitest.cr` on Travis.

### CODE REVIEW

**Comment by splattael** [comment]
@ysbaddaden I guess after https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com it's not enough to just put `.travis.yml` into the project, right?

¯\\___(ツ)___/¯

**Comment by ysbaddaden** [comment]
Why not just `language: crystal` instead of dealing with docker?

**Comment by splattael** [comment]
@ysbaddaden Oh, I've just learned that Travis supports both "latest" and "nightly":
https://docs.travis-ci.com/user/languages/crystal/

I'll change it, thanks!

**Comment by splattael** [comment]
@ysbaddaden Done. Again, thanks for the hint!

**Comment by ysbaddaden** [comment]
I removed `latest` as it doesn't work for `language: crystal`. Not a big deal, as `minitest` should be compatible with the latest crystal release.

**Comment by splattael** [comment]
@ysbaddaden Thanks for :twisted_rightwards_arrows: :purple_heart: 

The whole point of this PR was to test `minitest.cr` *also* on nightly Crystal to detect API changes earlier.

We've started to test nightly Crystal (allowing failures) to track the latest language/API changes.
This way we don't get overwhelmed when a new version is released.

**Comment by ysbaddaden** [comment]
I understand but:

1. it's hard to keep compatibility with both (latest, master) when there is a breaking change;
2. I want to stay as away of docker as possible.

**Comment by splattael** [comment]
@ysbaddaden Gotcha! Thanks again :)

**Pull request merged**
