### PR TITLE
Avoid using Channel::Buffered explicitly

### PR DESCRIPTION
**Pull request by bcardiff**
Fix compatibility for Crystal 0.31.0
This change is backward compatible.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Thanks, any reason for the explicitness change? I'll probably have to look at Earl, too.

**Comment by bcardiff** [comment]
I picked a buffer size that allowed a couple of specs to run before the main fiber received the messages. I think that this is preserving the old behavior regarding the buffer size but I’m not familiar with the default number of threads.

In crystal 0.31 there is only one Channel class.

**Comment by bcardiff** [comment]
Changes commited in fff29b0a8f45ffe8031ecdab0bf566b9189d13c0

**Comment by ysbaddaden** [comment]
Thanks for the input! I fixed this in master, and took advantage of Channel#close not closing the channel anymore, but to after the queue is emptied (a great change)!

**Pull request closed without merging**
