### PR TITLE
Extends list of matchers

### PR DESCRIPTION
**Pull request by imdrasil**
Added list of new matchers:
- change
- match_array
- be_truthy
- be_falsey
- instance_of

Also added "xit" to disable test case from compilation. Added let with class definition (sometimes we can get error of impossibility of class prediction from compiler). Added `after_all` callback method for `Runnable`.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
There are too many different things in this pull request. First of all, I'm sorry but I want to match Ruby's minitest and want to avoid rspec-isms and alikes.

We don't need `xit` because we have `skip` and `skip "helpful message"` instead. This will count skipped tests, report them, and list them along with the helpful message when `--verbose` is passed. Maybe `let` with optional type is useful.

What would `after_all` achieve? Tests are run each in their own instance, and in whatever order in parallel, and tests from a suite will span from the start to the end of the test run. If you need to do some cleanup, call `Minitest.after_run { ... }` (it may be called many times).

There are enough matchers. Maybe `assert_instance_of` could be added, but I still prefer `assert_equal Type, typeof(var)` which is more strict; use `assert` or `refute` instead of `be_truthy` and `be_falsey` (benefit of having both assertions and expectations), ...

**Comment by imdrasil** [comment]
I agree with `xit`, also I've just acidently missed `::after_run` (even don't know how) so it is also should be removed. About `be_truthy` and `be_falsey` could be added just for `spec` style. More interesting - what do you think about `change` ones?

**Comment by jkthorne** [comment]
@imdrasil what is the status of this PR?

**Comment by imdrasil** [comment]
I got to put it in the shelf but now I have free time to revoke my work. Will update this PR in few days

**Comment by ysbaddaden** [comment]
I added instance_of assertions & expections, see 1e36f6672d250585cf7247c2017777f77a990eae and 9a43dbd33c3364c41d725a064bf28f67ed647564. I don't think I'll merge more assertions / expectations.

**Pull request closed without merging**
