### PR TITLE
Compatibility with Crystal >= 0.27.0

### PR DESCRIPTION
**Pull request by bcardiff**
I wish I would be able to perform the check in a nicer way, but as today that is not possible.

Since shards depends on minitest.cr the nightly build has been failing since tempfile was removed.

This patch is a migration path that will allow minitest to keep running despite that breaking change. Future version could drop support of crystal < 0.27 if wanted.

It would be great to have a minitest release that could be used in shard.

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I pushed [v0.4.1](https://github.com/ysbaddaden/minitest.cr/releases/tag/v0.4.1) that requires Crystal 0.27.

**Comment by ysbaddaden** [comment]
Let's not worry about backward compatibility.

**Comment by bcardiff** [comment]
Ok, but that only works for shards and crystal because shard’s specs are
not run during the release of crystal. But shards is built using
nightly/tagged compiler. It’s in the edge of not having a smooth migration
path doing it that way.

> --
Brian J. Cardiff
[email] bcardiff@manas.tech
[web] https://manas.tech

**Comment by ysbaddaden** [comment]
Let's worry about smooth migrations when we'll stop introducing breaking changes, until then let's embrace running on the edge :mountain_biking_woman: 

Maybe Shard's master branch should only run against nightly builds of Crystal, and we could introduce `0.x-stable` branches for bugfixes that use a released Crystal.

**Pull request closed without merging**
